theme: jekyll-theme-minimal
image: https://drive.google.com/file/d/1hQmJNku6t9_6WXGDLRnZ9L94AdXinPDf/view?usp=sharing
title: Victoria Ruiz
description: Life Events Blog
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Syntax
    url: syntax
  - title: Example
    url: example
  - title: Resume
    url: assets/files/sample_resume.pdf

